name: Schedule Tests

on:
  schedule:
    - cron: '0/5 * * * 1-5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v3

      - name: Instalar Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Instalar Geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=firefox-ci -Dcucumber.options="--tags ~@ignore"

      - name: Gerar relatório
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://cdn-icons-png.flaticon.com/512/148/148767.png?size=48
          SLACK_MESSAGE: 'Sucesso na execução de testes Agendados :white_check_mark:'
          SLACK_TITLE: 'Sucesso na execução de testes Agendados :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://images.icon-icons.com/1378/PNG/512/dialogerror_92823.png?size=48
          SLACK_MESSAGE: 'Erro na execução de testes Agendados :fire:'
          SLACK_TITLE: 'Erro na execução de testes Agendados :fire:'
          SLACK_USERNAME: FALHA